import React,{useEffect,useMemo,useState} from "react";
const API=import.meta.env.VITE_API_BASE_URL||"";
const PRODUCTS=[
{id:1,c:"Beverages",n:"Americano",d:"Bold espresso lengthened with hot water.",p:140,r:4.8,img:"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=82",o:[["Size",["Small +0","Medium +20","Large +40"]],["Shot",["Single +0","Double +30","Triple +55"]]]},
{id:2,c:"Beverages",n:"Cappuccino",d:"Espresso, steamed milk and silky foam.",p:170,r:4.9,img:"https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=82",o:[["Size",["Small +0","Medium +20","Large +40"]],["Milk",["Regular +0","Oat +45","Almond +45"]]]},
{id:3,c:"Beverages",n:"Cold Brew",d:"Slow-steeped coffee served chilled.",p:190,r:4.8,img:"https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=82",o:[["Size",["Regular +0","Large +35"]]]},
{id:4,c:"Refreshments",n:"Mango Mint Cooler",d:"Fresh mango, lime, mint and crushed ice.",p:180,r:4.8,img:"https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=82",o:[["Ice",["Regular +0","Less ice +0","No ice +0"]]]},
{id:5,c:"Starters",n:"Paneer Tikka",d:"Charred paneer with peppers and smoky spices.",p:320,r:4.9,img:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=82",o:[["Spice",["Mild +0","Medium +0","Hot +0"]],["Portion",["Regular +0","Large +80"]]]},
{id:6,c:"Indian",n:"Butter Chicken",d:"Tandoori chicken in tomato-butter gravy.",p:420,r:4.9,img:"https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=82",o:[["Spice",["Mild +0","Medium +0","Hot +0"]],["Portion",["Regular +0","Large +110"]]]},
{id:7,c:"Indian",n:"Veg Biryani",d:"Fragrant basmati rice with vegetables and saffron.",p:330,r:4.7,img:"https://images.unsplash.com/photo-1563379091339-03246963d51a?auto=format&fit=crop&w=800&q=82",o:[["Spice",["Mild +0","Medium +0","Hot +0"]],["Raita",["None +0","Plain +40","Boondi +45"]]]},
{id:8,c:"Italian",n:"Margherita Pizza",d:"Tomato, mozzarella and basil on a crisp base.",p:420,r:4.9,img:"https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=82",o:[["Size",["10 inch +0","12 inch +100","14 inch +190"]],["Crust",["Thin +0","Regular +0","Stuffed +120"]],["Toppings",["Extra cheese +80","Mushrooms +60","Olives +60","Bell peppers +50"]]]},
{id:9,c:"Italian",n:"Penne Arrabbiata",d:"Penne tossed in tomato, garlic and chilli.",p:340,r:4.7,img:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=82",o:[["Spice",["Mild +0","Medium +0","Hot +0"]],["Add-on",["None +0","Chicken +110","Mushroom +80"]]]},
{id:10,c:"Desserts",n:"Tiramisu",d:"Espresso-soaked sponge, mascarpone and cocoa.",p:240,r:4.9,img:"https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=82",o:[]}
];
const CATS=["All","Beverages","Refreshments","Starters","Indian","Italian","Desserts"];
const extra=s=>Number((s.match(/\+\s*(\d+)/)||[])[1]||0);
function App(){
 const table=new URLSearchParams(location.search).get("table")||"12";
 const [cat,setCat]=useState("Beverages"),[search,setSearch]=useState(""),[cart,setCart]=useState(()=>JSON.parse(localStorage.getItem("ss-react-cart")||"[]")),[selected,setSelected]=useState(null),[choices,setChoices]=useState({}),[qty,setQty]=useState(1),[panel,setPanel]=useState(null),[customer,setCustomer]=useState({name:"",phone:"",preference:"",notes:""}),[sending,setSending]=useState(false),[error,setError]=useState(""),[order,setOrder]=useState(()=>JSON.parse(localStorage.getItem("ss-react-order")||"null"));
 useEffect(()=>localStorage.setItem("ss-react-cart",JSON.stringify(cart)),[cart]);\n useEffect(()=>{const sync=()=>{const saved=JSON.parse(localStorage.getItem("ss-react-order")||"null");if(!saved?.orderId)return;const list=JSON.parse(localStorage.getItem("ss-orders")||"[]");const latest=list.find(x=>x.orderId===saved.orderId);if(latest)setOrder(latest)};sync();const t=setInterval(sync,1000);window.addEventListener("storage",sync);return()=>{clearInterval(t);window.removeEventListener("storage",sync)}},[]);
 const total=useMemo(()=>cart.reduce((a,x)=>a+x.unit*x.qty,0),[cart]);
 const list=useMemo(()=>PRODUCTS.filter(x=>(cat==="All"||x.c===cat)&&(!search||(x.n+" "+x.d+" "+x.c).toLowerCase().includes(search.toLowerCase()))),[cat,search]);
 const unit=selected?selected.p+Object.values(choices).reduce((a,x)=>a+extra(x),0):0;
 function openProduct(p){const init={};p.o.forEach(([g,opts])=>init[g]=opts[0]);setChoices(init);setQty(1);setSelected(p);setPanel("item")}
 function addProduct(){const key=selected.id+"|"+Object.values(choices).join("|");setCart(v=>{const found=v.find(x=>x.key===key);if(found)return v.map(x=>x.key===key?{...x,qty:Math.min(10,x.qty+qty)}:x);return [...v,{key,name:selected.n,img:selected.img,unit,qty,choices:Object.values(choices)}]});setPanel("cart")}
 function change(i,d){setCart(v=>v.map((x,k)=>k===i?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0))}
 async function placeOrder(){
   if(customer.name.trim().length<2||!/^[+0-9()\-\s]{7,20}$/.test(customer.phone.trim())){setError("Enter a valid name and phone number.");return}
   if(!cart.length)return; setSending(true);setError("");
   const idempotencyKey=crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();
   const payload={idempotencyKey,tableNumber:table,customer:{name:customer.name.trim(),phone:customer.phone.trim()},dietaryPreference:customer.preference||null,specialInstructions:customer.notes.trim()||null,items:cart.map(x=>({name:x.name,quantity:x.qty,unitPrice:x.unit,customizations:x.choices}))};
   try{
     let result=null;
     if(API){const r=await fetch(API+"/api/v1/orders",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Backend rejected the order");result=await r.json();}
     else {result={orderId:"DEMO-"+Math.floor(100000+Math.random()*900000),status:"NEW",...payload,createdAt:new Date().toISOString()};const orders=JSON.parse(localStorage.getItem("ss-orders")||"[]");orders.unshift(result);localStorage.setItem("ss-orders",JSON.stringify(orders));window.dispatchEvent(new StorageEvent("storage",{key:"ss-orders",newValue:JSON.stringify(orders)}))}
     localStorage.setItem("ss-react-order",JSON.stringify(result));setOrder(result);setCart([]);setPanel("status");setCustomer({name:"",phone:"",preference:"",notes:""});
   }catch(e){setError("We could not reach the restaurant. Your cart is still saved. Retry when the connection is available.");}
   finally{setSending(false)}
 }
 return <><header className="top"><div className="topin"><div className="brand">Saffron &amp; Stone</div><div className="table">TABLE {table}</div><button className="cartBtn" onClick={()=>setPanel("cart")}>🛒 Cart <span>{cart.reduce((a,x)=>a+x.qty,0)}</span> · ₹{total}</button></div></header>
 <main className="wrap"><section className="hero"><div className="heroMain"><div className="ey">TABLE {table} · ORDER ONLINE</div><h1>What are you craving?</h1><p>Browse the menu, customize every dish, and send your order straight to the restaurant.</p></div><aside className="side"><div><b>🍕 10% off pizzas</b><small>Orders above ₹600</small></div><div><b>☕ Coffee pairings</b><small>Ask for today's pairing</small></div><div><b>🌶️ Spice control</b><small>Choose your heat level</small></div></aside></section>
 <input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search pizza, coffee, biryani, dessert…"/>
 <nav className="cats">{CATS.map(c=><button key={c} className={cat===c?"active":""} onClick={()=>setCat(c)}>{c}</button>)}</nav>
 <section className="section"><div className="head"><div><h2>{cat==="All"?"All dishes":cat}</h2><span>Tap Add to customize</span></div><span>{list.length} dishes</span></div><div className="grid">{list.map(p=><article className="card" key={p.id}><img src={p.img} alt={p.n}/><div className="body"><h3>{p.n}</h3><p>{p.d}</p><div className="meta"><div><strong>₹{p.p}</strong><small>★ {p.r}</small></div><button onClick={()=>openProduct(p)}>Add</button></div></div></article>)}</div>{!list.length&&<div className="empty">No matching dishes.</div>}</section>
 <footer>Table {table} · Saffron &amp; Stone</footer></main>
 {panel==="item"&&selected&&<div className="overlay" onClick={e=>e.target===e.currentTarget&&setPanel(null)}><div className="sheet"><div className="ph"><div><div className="ey">CUSTOMIZE</div><h2>{selected.n}</h2></div><button onClick={()=>setPanel(null)}>×</button></div><p className="muted">{selected.d}</p>{selected.o.map(([g,opts])=><div className="option" key={g}><b>{g}</b><div className="opts">{opts.map(o=><button key={o} className={choices[g]===o?"selected":""} onClick={()=>setChoices(v=>({...v,[g]:o}))}>{o}</button>)}</div></div>)}<div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(Math.min(10,qty+1))}>+</button><strong>₹{unit*qty}</strong></div><button className="primary" onClick={addProduct}>Add to cart · ₹{unit*qty}</button></div></div>}
 {panel==="cart"&&<div className="overlay" onClick={e=>e.target===e.currentTarget&&setPanel(null)}><div className="sheet"><div className="ph"><div><div className="ey">YOUR ORDER</div><h2>Cart</h2></div><button onClick={()=>setPanel(null)}>×</button></div>{cart.length?cart.map((x,i)=><div className="line" key={x.key}><img src={x.img} alt=""/><div><b>{x.name}</b><small>{x.choices.join(" · ")}</small><small>₹{x.unit} × {x.qty}</small></div><div className="lineQty"><button onClick={()=>change(i,-1)}>−</button>{x.qty}<button onClick={()=>change(i,1)}>+</button></div></div>):<div className="empty">Your cart is empty.</div>}<div className="sum"><span>Table {table}</span><b>₹{total}</b></div>{cart.length>0&&<button className="primary" onClick={()=>setPanel("checkout")}>Continue to checkout</button>}</div></div>}
 {panel==="checkout"&&<div className="overlay"><div className="sheet"><div className="ph"><div><div className="ey">CHECKOUT</div><h2>Send to restaurant</h2></div><button onClick={()=>setPanel("cart")}>←</button></div><div className="notice">📍 Table {table} came from the QR code.</div><div className="fields"><input placeholder="Your name" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/><input placeholder="Phone number" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/><select value={customer.preference} onChange={e=>setCustomer({...customer,preference:e.target.value})}><option value="">Dietary preference</option><option>Vegetarian</option><option>Vegan</option><option>Jain</option><option>No onion / garlic</option></select><textarea rows="3" placeholder="Special instructions" value={customer.notes} onChange={e=>setCustomer({...customer,notes:e.target.value})}/></div>{error&&<div className="error">{error}</div>}<button className="primary" disabled={sending} onClick={placeOrder}>{sending?"Sending order…":"Place order · ₹"+total}</button></div></div>}
 {panel==="status"&&order&&<div className="overlay"><div className="sheet"><div className="ph"><div><div className="ey">ORDER RECEIVED</div><h2>{order.orderId}</h2></div><button onClick={()=>setPanel(null)}>×</button></div><p className="muted">Table {table} · Your order has been sent to the restaurant.</p><div className="statusList">{[["NEW","Order placed"],["ACCEPTED","Accepted by restaurant"],["PREPARING","Preparing"],["READY","Ready"],["COMPLETED","Completed"]].map(([code,s])=><div key={code} className={order.status===code?"stage active":"stage"}>{order.status===code?"✓ ":"○ "}{s}</div>)}</div></div></div>}
 <div className="bottom"><span>🛒 {cart.reduce((a,x)=>a+x.qty,0)||"Your cart is empty"}</span><b>₹{total}</b></div></>}
export default App;